natlas-server/app/user/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, SelectField
from wtforms.validators import DataRequired, ValidationError, EqualTo, Length
from app.models import User

class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Old Password', validators=[DataRequired()])
    password = PasswordField('Password', validators=[
                             DataRequired(), Length(min=8)])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    changePassword = SubmitField('Change Password')

    def validate_old_password(self, old_password):
        user = User.query.get(current_user.id)
        if user is None:
            raise ValidationError("You're not logged in!")
        if not user.check_password(old_password.data):
            raise ValidationError("Invalid password! If you forgot your password, please use the password reset form.")

class DisplaySettingsForm(FlaskForm):
    results_per_page = SelectField('Results Per Page', coerce=int)
    preview_length = SelectField('Preview Length', coerce=int)
    updateDisplaySettings = SubmitField("Submit Changes")


class GenerateTokenForm(FlaskForm):
    generateToken = SubmitField("Generate Token")

class AgentNameForm(FlaskForm):
    agent_name = StringField("New Agent Name", validators=[DataRequired()])
    change_name = SubmitField("Change Name")

    def validate_agent_name(self, agent_name):
        if len(agent_name.data) > 32:
            raise ValidationError("Name must be less than 32 characters")

natlas-server/app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

natlas-server/app/user/routes.py
from flask import render_template, redirect, url_for, current_app, flash, Response, abort, request
from flask_login import current_user
from app import db
from app.user import bp
from app.user.forms import ChangePasswordForm, DisplaySettingsForm, GenerateTokenForm, AgentNameForm
from app.models import User, Agent
from app.auth.wrappers import isAuthenticated, isAdmin
import ipaddress

@bp.route('/', methods=['GET', 'POST'])
@isAuthenticated
def profile():
    # Handle this case because isAuthenticated only applies when LOGIN_REQUIRED is true
    if current_user.is_anonymous:
        flash("You must be a user to access %s" % request.path, "warning")
        return redirect(url_for('main.index'))
    myagents = current_user.agents
    changePasswordForm = ChangePasswordForm(prefix="change-password")
    displaySettingsForm = DisplaySettingsForm(prefix="display-settings", results_per_page=current_user.results_per_page, \
        preview_length=current_user.preview_length)
    displaySettingsForm.results_per_page.choices = [(25,25), (50,50), (75,75), (100,100)]
    displaySettingsForm.preview_length.choices = [(25,25), (50,50), (75,75), (100,100)]

    generateTokenForm = GenerateTokenForm()
    agentNameForm = AgentNameForm()

    if changePasswordForm.changePassword.data and changePasswordForm.validate_on_submit():
            user = User.query.get(current_user.id)
            user.set_password(changePasswordForm.password.data)
            db.session.commit()
            flash('Your password has been changed.', "success")
            return redirect(url_for('user.profile'))
    if displaySettingsForm.updateDisplaySettings.data and displaySettingsForm.validate_on_submit():
            user = User.query.get(current_user.id)
            user.results_per_page = displaySettingsForm.results_per_page.data
            user.preview_length = displaySettingsForm.preview_length.data
            db.session.commit()
            flash("Display settings updated.", "success")
            return redirect(url_for('user.profile'))
    if agentNameForm.change_name.data and agentNameForm.validate_on_submit():
        return redirect(url_for('user.profile'))
    return render_template("user/profile.html", changePasswordForm=changePasswordForm, displaySettingsForm=displaySettingsForm, \
        agents=myagents, generateTokenForm=generateTokenForm, agentNameForm=agentNameForm)

@bp.route('/agent/<string:agent_id>/newToken', methods=['POST'])
@isAuthenticated
def generateNewToken(agent_id):
    generateTokenForm = GenerateTokenForm()

    if generateTokenForm.validate_on_submit():
        myAgent = Agent.load_agent(agent_id)
        myAgent.token = Agent.generate_token()
        db.session.commit()
        flash("Agent %s has a new key of: %s" % (myAgent.agentid, myAgent.token), "success")
        return redirect(request.referrer)
    else:
        flash("Couldn't generate new token", "danger")
        return redirect(request.referrer)

@bp.route('/agent/<string:agent_id>/newName', methods=['POST'])
@isAuthenticated
def changeAgentName(agent_id):
    agentNameForm = AgentNameForm()

    if agentNameForm.validate_on_submit():
        myAgent = Agent.load_agent(agent_id)
        oldname = myAgent.friendly_name
        myAgent.friendly_name = agentNameForm.agent_name.data
        db.session.commit()
        flash("Agent name changed from %s to %s" % (oldname, myAgent.friendly_name), "success")
        return redirect(request.referrer)
    else:
        flash("Couldn't change agent name", "danger")
        return redirect(request.referrer)

@bp.route('/agent/newAgent', methods=['POST'])
@isAuthenticated
def newAgent():
    newAgentForm = AgentNameForm()

    if newAgentForm.validate_on_submit():
        myAgent = Agent(user_id=current_user.id, agentid=Agent.generate_agentid(), token=Agent.generate_token(), \
            friendly_name=newAgentForm.agent_name.data)
        db.session.add(myAgent)
        db.session.commit()
        flash("New Agent named %s created. Agent ID: %s Agent Token: %s" \
            % (myAgent.friendly_name, myAgent.agentid, myAgent.token), "success")
        return redirect(request.referrer)
    else:
        flash("Couldn't create new agent", "danger")
        return redirect(request.referrer)

natlas-server/app/templates/user/_agent_menu.html
<div class="btn-group dropright">
    <button class="btn btn-lg dropdown-toggle dropdown-no-arrow" type="button" id="adminMenu-{{loop.index}}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-ellipsis-v"></i>
    </button>
    <div class="dropdown-menu" aria-labelledby="adminMenu-{{loop.index}}">
        <form method="POST" action="{{ url_for('user.generateNewToken', agent_id=agent.agentid) }}">{{ generateTokenForm.hidden_tag() }} <button class="btn inline-submit" id="refreshToken-{{loop.index}}" name="generateToken" title="Refresh Token" onclick="return confirm('Are you sure you want to generate a new token for {{ agent.agentid }}? This will invalidate any existing agents using this token.')" type="submit" ><i class="fas fa-sync-alt text-info mr-1"></i>Refresh Token</button></form>
      <button class="btn" id="agentName-{{loop.index}}" name="changename" title="Change Agent Name" data-toggle="modal" data-target="#agentmodal" data-agentid="{{agent.agentid}}" data-agentname="{{agent.friendly_name}}" data-action="changename" type="button"><i class="fas fa-pencil-alt text-info mr-1"></i>Change Name</button>
    </div>
</div>

natlas-server/app/templates/user/_header.html
<div class="row">
	<div class="page-header">
	    <h1>{{ current_user.email }}</h1>
	</div>
</div>

natlas-server/app/templates/user/profile.html
{% extends "base.html" %}
{% set title = current_user.email ~ " | Profile" %}
{% set active_page = "profile" %}
{% block content %}
        {% include 'user/_header.html' %}
    	<div class="row">
	    	<div class="col-xs-12 col-sm-6 col-md-4">
	    		<h3>Change Password</h3>
		    	<form class="form-horizontal pwchange-form" action="{{url_for('user.profile')}}" method="post">
                    {{ changePasswordForm.hidden_tag() }}
			    	<div class="form-group">
			    		{{ changePasswordForm.old_password.label(class="control-label") }}
			    		{{ changePasswordForm.old_password(class="form-control") }}
			    		{% for error in changePasswordForm.old_password.errors %}
		                <span style="color: red;">{{ error }}</span>
		                {% endfor %}
			    	</div>
			    	<div class="form-group">
			    		{{ changePasswordForm.password.label(class="control-label") }}
			    		{{ changePasswordForm.password(class="form-control") }}
			    		{% for error in changePasswordForm.password.errors %}
		                <span style="color: red;">{{ error }}</span>
		                {% endfor %}
			    	</div>
			    	<div class="form-group">
			    		{{ changePasswordForm.password2.label(class="control-label") }}
			    		{{ changePasswordForm.password2(class="form-control") }}
			    		{% for error in changePasswordForm.password2.errors %}
		                <span style="color: red;">{{ error }}</span>
		                {% endfor %}
			    	</div>
			    	<div>{{ changePasswordForm.changePassword(class="btn btn-primary") }}</div>
		    	</form>
		    </div>
            <div class="col-xs-12 col-sm-5 col-sm-offset-1 col-md-3 col-md-offset-1">
                <h3>Display Settings</h3>
                <form class="form-horizontal display-form" action="{{url_for('user.profile')}}" method="post">
                    {{ displaySettingsForm.hidden_tag() }}
                    <div class="form-group">
                        {{ displaySettingsForm.results_per_page.label(class="control-label") }}
                        {{ displaySettingsForm.results_per_page(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ displaySettingsForm.preview_length.label(class="control-label") }}
                        {{ displaySettingsForm.preview_length(class="form-control") }}
                    </div>
                    <div>{{ displaySettingsForm.updateDisplaySettings(class="btn btn-primary") }}</div>
                </form>
            </div>
		</div>
        <div class="row">
            <div class="col-12 my-3 border-bottom d-flex justify-content-between">
                <h2 class="d-inline-block">My Agents</h2>
                <div class="d-inline-block mb-2" style="font-size:2rem;">
                    <button class="btn btn-success" id="newAgent" name="newagent" title="Create New Agent" data-toggle="modal" data-target="#agentmodal" data-agentid="None" data-agentname="None" data-action="newagent" type="button"><i class="fas fa-plus-circle text-white mr-1"></i>New Agent</button>
                </div>
            </div>
            {% if agents %}
            <div class="col-12">
                <table class="table table-striped dataTable">
                    <thead>
                      <tr>
                        <th scope="col">Date Created</th>
                        <th scope="col">Agent ID</th>
                        <th scope="col">Friendly Name</th>
                        <th scope="col">API Key</th>
                        <th class="table-controls" scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for agent in agents %}
                      <tr id="agentrow-{{loop.index}}">
                        <td><time datetime="{{ agent.date_created.strftime('%Y-%m-%d %H:%M') }}" title="{{ agent.date_created.strftime('%Y-%m-%d %H:%M %Z') }}">{{ agent.date_created.strftime('%Y-%m-%d %H:%M') }}</time></td>
                        <td class="text-monospace">{{ agent.agentid }}</td>
                        <td>{{ agent.friendly_name }}</td>
                        <td id="agenttoken-{{loop.index}}" class="text-monospace">
                            <div id="showtokenwrapper-{{loop.index}}"><a id="showtoken-{{loop.index}}" class="showtoken" style="cursor:pointer;">Show API Key</a>{% if loop.index == 1%}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{% endif %}</div>
                            <div class="tokenval" id="tokenval-{{loop.index}}" style="display:none;">{{ agent.token }}</div>
                        </td> 
                        <td style="text-align:center;">
                          {% include 'user/_agent_menu.html' %}
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>
            {% endif %}
        </div>

<div class="modal fade" tabindex="-1" role="dialog" id="agentmodal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Change Agent Name</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" action="{{url_for('user.newAgent')}}" id="agentNameForm">
      <div class="modal-body">
          {{ agentNameForm.hidden_tag() }}
          {{ agentNameForm.agent_name(size=32, class="form-control", placeholder="Agent 1") }}
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="submit" id="change_name" class="btn btn-primary">Change Name</button>
      </div>
      </form>
    </div>
  </div>
</div>

<script>
$('#agentmodal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var agentid = button.data('agentid') // Extract info from data-* attributes
  var agentname = button.data('agentname') // Extract info from data-* attributes
  var formaction = button.data('action')

  var modal = $(this)
  if (formaction == 'changename') {
    modal.find('.modal-title').text('Change Name of ' + agentid)
    modal.find('#agentNameForm').attr('action', "/user/agent/"+agentid+"/newName")
    modal.find('#change_name').text('Change Name')
    modal.find("#agent_name").attr('placeholder', agentname)
  } else if (formaction == 'newagent') {
    modal.find('.modal-title').text('New Agent')
    modal.find('#agentNameForm').attr('action', '/user/agent/newAgent')
    modal.find('#change_name').text('New Agent')
  } 
})

$('.showtoken').on('click', function() {
        var tokentarget = event.target.id.split("-")[1];
        $(event.target).hide();
        $('#showtokenwrapper-' + tokentarget).hide();
        $('#tokenval-' + tokentarget).show();
})
</script>
{% endblock %}